collections:
  - name: berita
    label: Berita
    folder: berita
    create: true
    slug: "{{slug}}"

    fields:
      - name: title
        label: Judul
        type: text

      - name: date
        label: Tanggal
        type: datetime

      - name: description
        label: Meta Description
        type: textarea

      - name: image
        label: Featured Image
        type: image

      - name: body
        label: Isi Artikel
        type: markdown