backend:
  name: github
  repo: billiemy/beritapsg
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

site_url: https://beritapsg.com
display_url: https://beritapsg.com

publish_mode: editorial_workflow

collections:
  - name: "berita"
    label: "Berita PSG"
    folder: "berita"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - { label: "Judul Berita", name: "title", widget: "string" }

      - { label: "Tanggal Publikasi", name: "date", widget: "datetime" }

      - { label: "Meta Description", name: "description", widget: "text" }

      - { label: "Canonical URL", name: "canonical", widget: "string", required: false }

      - { label: "Featured Image", name: "image", widget: "image", required: false }

      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }

      - { label: "Isi Artikel", name: "body", widget: "markdown" }