backend:
  name: github
  repo: billiemy/beritapsg
  branch: main
  auth_type: pkce

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "posts"
    label: "Berita"
    folder: "berita"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Meta Description", name: "description", widget: "text" }
      - { label: "Canonical", name: "canonical", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }